// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listAuditLog = `-- name: ListAuditLog :many
SELECT aa.id,
       aa.action,
       aa.target_id,
       aa.detail,
       aa.created_at,
       COALESCE(u.username::text, '')::text  AS actor,
       COALESCE(ap.username::text, '')::text AS approver
FROM admin_actions aa
LEFT JOIN users u  ON u.id  = aa.actor_user_id
LEFT JOIN users ap ON ap.id = aa.approved_by
WHERE ($1::timestamptz IS NULL
       OR (aa.created_at, aa.id) < ($1::timestamptz, $2::uuid))
  AND (
      $3::text IS NULL OR $3::text = ''
   OR aa.action ILIKE '%' || $3 || '%'
   OR u.username::text ILIKE '%' || $3 || '%'
   OR aa.detail::text ILIKE '%' || $3 || '%'
  )
ORDER BY aa.created_at DESC, aa.id DESC
LIMIT $4::int
`

type ListAuditLogParams struct {
	Cursor    *time.Time `json:"cursor"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Q         *string    `json:"q"`
	PageLimit int32      `json:"page_limit"`
}

type ListAuditLogRow struct {
	ID        uuid.UUID  `json:"id"`
	Action    string     `json:"action"`
	TargetID  *uuid.UUID `json:"target_id"`
	Detail    []byte     `json:"detail"`
	CreatedAt time.Time  `json:"created_at"`
	Actor     string     `json:"actor"`
	Approver  string     `json:"approver"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Cursor,
		arg.CursorID,
		arg.Q,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogRow
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
			&i.Actor,
			&i.Approver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdminAction = `-- name: RecordAdminAction :exec
INSERT INTO admin_actions (actor_user_id, action, target_id, detail)
VALUES (
    $1::uuid,
    $2::text,
    $3::uuid,
    $4::jsonb
)
`

type RecordAdminActionParams struct {
	ActorUserID uuid.UUID  `json:"actor_user_id"`
	Action      string     `json:"action"`
	TargetID    *uuid.UUID `json:"target_id"`
	Detail      []byte     `json:"detail"`
}

func (q *Queries) RecordAdminAction(ctx context.Context, arg RecordAdminActionParams) error {
	_, err := q.db.Exec(ctx, recordAdminAction,
		arg.ActorUserID,
		arg.Action,
		arg.TargetID,
		arg.Detail,
	)
	return err
}
