// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console.sql

package sqlc

import (
	"context"
)

const dashboardStats = `-- name: DashboardStats :one
SELECT
    (SELECT count(*) FROM transfers WHERE status = 'pending')::bigint                       AS pending_count,
    (SELECT count(*) FROM holds WHERE status = 'active')::bigint                            AS active_holds,
    (SELECT COALESCE(SUM(amount_minor), 0) FROM holds WHERE status = 'active')::bigint      AS held_minor,
    (SELECT COALESCE(SUM(balance_minor), 0) FROM accounts WHERE kind = 'customer')::bigint  AS customer_money
`

type DashboardStatsRow struct {
	PendingCount  int64 `json:"pending_count"`
	ActiveHolds   int64 `json:"active_holds"`
	HeldMinor     int64 `json:"held_minor"`
	CustomerMoney int64 `json:"customer_money"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.ActiveHolds,
		&i.HeldMinor,
		&i.CustomerMoney,
	)
	return i, err
}
