// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const dashboardStats = `-- name: DashboardStats :one
SELECT
    (SELECT count(*) FROM transfers WHERE status = 'pending')::bigint                       AS pending_count,
    (SELECT count(*) FROM holds WHERE status = 'active')::bigint                            AS active_holds,
    (SELECT COALESCE(SUM(amount_minor), 0) FROM holds WHERE status = 'active')::bigint      AS held_minor,
    (SELECT COALESCE(SUM(balance_minor), 0) FROM accounts WHERE kind = 'customer')::bigint  AS customer_money
`

type DashboardStatsRow struct {
	PendingCount  int64 `json:"pending_count"`
	ActiveHolds   int64 `json:"active_holds"`
	HeldMinor     int64 `json:"held_minor"`
	CustomerMoney int64 `json:"customer_money"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.ActiveHolds,
		&i.HeldMinor,
		&i.CustomerMoney,
	)
	return i, err
}

const listCustomerAccounts = `-- name: ListCustomerAccounts :many
SELECT a.id,
       a.user_id,
       COALESCE(u.full_name, '') AS owner,
       COALESCE(a.iban, '')      AS iban,
       a.status,
       a.balance_minor,
       account_available(a.id)   AS available_minor
FROM accounts a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.kind = 'customer'
ORDER BY a.created_at DESC
LIMIT $1::int
`

type ListCustomerAccountsRow struct {
	ID             uuid.UUID     `json:"id"`
	UserID         *uuid.UUID    `json:"user_id"`
	Owner          string        `json:"owner"`
	Iban           string        `json:"iban"`
	Status         AccountStatus `json:"status"`
	BalanceMinor   int64         `json:"balance_minor"`
	AvailableMinor int64         `json:"available_minor"`
}

func (q *Queries) ListCustomerAccounts(ctx context.Context, pageLimit int32) ([]ListCustomerAccountsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerAccounts, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerAccountsRow
	for rows.Next() {
		var i ListCustomerAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Owner,
			&i.Iban,
			&i.Status,
			&i.BalanceMinor,
			&i.AvailableMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEnriched = `-- name: ListPendingEnriched :many
SELECT t.id,
       COALESCE(da.iban, da.system_code, '') AS debit,
       COALESCE(ca.iban, ca.system_code, '') AS credit,
       t.kind,
       t.description,
       t.amount_minor,
       t.requested_at
FROM transfers t
JOIN accounts da ON da.id = t.debit_account_id
JOIN accounts ca ON ca.id = t.credit_account_id
WHERE t.status = 'pending'
ORDER BY t.requested_at DESC
LIMIT $1::int
`

type ListPendingEnrichedRow struct {
	ID          uuid.UUID    `json:"id"`
	Debit       string       `json:"debit"`
	Credit      string       `json:"credit"`
	Kind        TransferKind `json:"kind"`
	Description string       `json:"description"`
	AmountMinor int64        `json:"amount_minor"`
	RequestedAt time.Time    `json:"requested_at"`
}

func (q *Queries) ListPendingEnriched(ctx context.Context, pageLimit int32) ([]ListPendingEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listPendingEnriched, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingEnrichedRow
	for rows.Next() {
		var i ListPendingEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.Debit,
			&i.Credit,
			&i.Kind,
			&i.Description,
			&i.AmountMinor,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
