// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const decideDispute = `-- name: DecideDispute :one
SELECT decide_dispute($1::uuid, $2::uuid,
    $3::dispute_decision, $4::bigint,
    $5::boolean, $6::text) AS payout_minor
`

type DecideDisputeParams struct {
	DisputeID      uuid.UUID       `json:"dispute_id"`
	Resolver       uuid.UUID       `json:"resolver"`
	Decision       DisputeDecision `json:"decision"`
	ReimburseMinor *int64          `json:"reimburse_minor"`
	Vulnerable     *bool           `json:"vulnerable"`
	Note           string          `json:"note"`
}

func (q *Queries) DecideDispute(ctx context.Context, arg DecideDisputeParams) (int64, error) {
	row := q.db.QueryRow(ctx, decideDispute,
		arg.DisputeID,
		arg.Resolver,
		arg.Decision,
		arg.ReimburseMinor,
		arg.Vulnerable,
		arg.Note,
	)
	var payout_minor int64
	err := row.Scan(&payout_minor)
	return payout_minor, err
}

const getDisputeAdmin = `-- name: GetDisputeAdmin :one
SELECT d.id, d.transfer_id, d.status, d.category, d.reason, d.resolution_note,
       d.scam_type, d.sla_due_at, d.decision, d.reimbursed_amount_minor, d.vulnerable_flag,
       d.recall_status, d.recall_reason, t.currency, d.created_at, d.updated_at
FROM disputes d
JOIN transfers t ON t.id = d.transfer_id
WHERE d.id = $1::uuid
`

type GetDisputeAdminRow struct {
	ID                    uuid.UUID       `json:"id"`
	TransferID            uuid.UUID       `json:"transfer_id"`
	Status                DisputeStatus   `json:"status"`
	Category              DisputeCategory `json:"category"`
	Reason                string          `json:"reason"`
	ResolutionNote        string          `json:"resolution_note"`
	ScamType              *string         `json:"scam_type"`
	SlaDueAt              *time.Time      `json:"sla_due_at"`
	Decision              DisputeDecision `json:"decision"`
	ReimbursedAmountMinor *int64          `json:"reimbursed_amount_minor"`
	VulnerableFlag        bool            `json:"vulnerable_flag"`
	RecallStatus          RecallStatus    `json:"recall_status"`
	RecallReason          string          `json:"recall_reason"`
	Currency              string          `json:"currency"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

func (q *Queries) GetDisputeAdmin(ctx context.Context, id uuid.UUID) (GetDisputeAdminRow, error) {
	row := q.db.QueryRow(ctx, getDisputeAdmin, id)
	var i GetDisputeAdminRow
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Status,
		&i.Category,
		&i.Reason,
		&i.ResolutionNote,
		&i.ScamType,
		&i.SlaDueAt,
		&i.Decision,
		&i.ReimbursedAmountMinor,
		&i.VulnerableFlag,
		&i.RecallStatus,
		&i.RecallReason,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisputeForRaiser = `-- name: GetDisputeForRaiser :one
SELECT d.id, d.transfer_id, d.status, d.category, d.reason, d.resolution_note,
       d.scam_type, d.sla_due_at, d.decision, d.reimbursed_amount_minor, d.vulnerable_flag,
       d.recall_status, d.recall_reason, t.currency, d.created_at, d.updated_at
FROM disputes d
JOIN transfers t ON t.id = d.transfer_id
WHERE d.id = $1::uuid AND d.raised_by_user_id = $2::uuid
`

type GetDisputeForRaiserParams struct {
	ID     uuid.UUID `json:"id"`
	Raiser uuid.UUID `json:"raiser"`
}

type GetDisputeForRaiserRow struct {
	ID                    uuid.UUID       `json:"id"`
	TransferID            uuid.UUID       `json:"transfer_id"`
	Status                DisputeStatus   `json:"status"`
	Category              DisputeCategory `json:"category"`
	Reason                string          `json:"reason"`
	ResolutionNote        string          `json:"resolution_note"`
	ScamType              *string         `json:"scam_type"`
	SlaDueAt              *time.Time      `json:"sla_due_at"`
	Decision              DisputeDecision `json:"decision"`
	ReimbursedAmountMinor *int64          `json:"reimbursed_amount_minor"`
	VulnerableFlag        bool            `json:"vulnerable_flag"`
	RecallStatus          RecallStatus    `json:"recall_status"`
	RecallReason          string          `json:"recall_reason"`
	Currency              string          `json:"currency"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

func (q *Queries) GetDisputeForRaiser(ctx context.Context, arg GetDisputeForRaiserParams) (GetDisputeForRaiserRow, error) {
	row := q.db.QueryRow(ctx, getDisputeForRaiser, arg.ID, arg.Raiser)
	var i GetDisputeForRaiserRow
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Status,
		&i.Category,
		&i.Reason,
		&i.ResolutionNote,
		&i.ScamType,
		&i.SlaDueAt,
		&i.Decision,
		&i.ReimbursedAmountMinor,
		&i.VulnerableFlag,
		&i.RecallStatus,
		&i.RecallReason,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDisputesAdmin = `-- name: ListDisputesAdmin :many
SELECT d.id, d.transfer_id, d.status, d.category, d.reason,
       d.scam_type, d.sla_due_at, d.decision, d.reimbursed_amount_minor,
       d.vulnerable_flag, d.recall_status, d.recall_reason,
       t.amount_minor, t.currency,
       COALESCE(u.username::text, '')        AS raised_by,
       COALESCE(da.iban, da.system_code, '') AS debit_iban,
       COALESCE(ca.iban, ca.system_code, '') AS credit_iban,
       d.created_at
FROM disputes d
JOIN transfers t  ON t.id  = d.transfer_id
LEFT JOIN users u ON u.id  = d.raised_by_user_id
JOIN accounts da  ON da.id = t.debit_account_id
JOIN accounts ca  ON ca.id = t.credit_account_id
WHERE ($1::dispute_status IS NULL OR d.status = $1::dispute_status)
  AND ($2::timestamptz IS NULL
       OR (d.created_at, d.id) < ($2::timestamptz, $3::uuid))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $4::int
`

type ListDisputesAdminParams struct {
	Status    NullDisputeStatus `json:"status"`
	Cursor    *time.Time        `json:"cursor"`
	CursorID  *uuid.UUID        `json:"cursor_id"`
	PageLimit int32             `json:"page_limit"`
}

type ListDisputesAdminRow struct {
	ID                    uuid.UUID       `json:"id"`
	TransferID            uuid.UUID       `json:"transfer_id"`
	Status                DisputeStatus   `json:"status"`
	Category              DisputeCategory `json:"category"`
	Reason                string          `json:"reason"`
	ScamType              *string         `json:"scam_type"`
	SlaDueAt              *time.Time      `json:"sla_due_at"`
	Decision              DisputeDecision `json:"decision"`
	ReimbursedAmountMinor *int64          `json:"reimbursed_amount_minor"`
	VulnerableFlag        bool            `json:"vulnerable_flag"`
	RecallStatus          RecallStatus    `json:"recall_status"`
	RecallReason          string          `json:"recall_reason"`
	AmountMinor           int64           `json:"amount_minor"`
	Currency              string          `json:"currency"`
	RaisedBy              interface{}     `json:"raised_by"`
	DebitIban             string          `json:"debit_iban"`
	CreditIban            string          `json:"credit_iban"`
	CreatedAt             time.Time       `json:"created_at"`
}

func (q *Queries) ListDisputesAdmin(ctx context.Context, arg ListDisputesAdminParams) ([]ListDisputesAdminRow, error) {
	rows, err := q.db.Query(ctx, listDisputesAdmin,
		arg.Status,
		arg.Cursor,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputesAdminRow
	for rows.Next() {
		var i ListDisputesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Status,
			&i.Category,
			&i.Reason,
			&i.ScamType,
			&i.SlaDueAt,
			&i.Decision,
			&i.ReimbursedAmountMinor,
			&i.VulnerableFlag,
			&i.RecallStatus,
			&i.RecallReason,
			&i.AmountMinor,
			&i.Currency,
			&i.RaisedBy,
			&i.DebitIban,
			&i.CreditIban,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesForRaiser = `-- name: ListDisputesForRaiser :many
SELECT d.id, d.transfer_id, d.status, d.category, d.reason, d.resolution_note,
       d.scam_type, d.sla_due_at, d.decision, d.reimbursed_amount_minor, d.vulnerable_flag,
       d.recall_status, d.recall_reason, t.currency, d.created_at, d.updated_at
FROM disputes d
JOIN transfers t ON t.id = d.transfer_id
WHERE d.raised_by_user_id = $1::uuid
  AND ($2::timestamptz IS NULL OR d.created_at < $2::timestamptz)
ORDER BY d.created_at DESC
LIMIT $3::int
`

type ListDisputesForRaiserParams struct {
	Raiser    uuid.UUID  `json:"raiser"`
	Cursor    *time.Time `json:"cursor"`
	PageLimit int32      `json:"page_limit"`
}

type ListDisputesForRaiserRow struct {
	ID                    uuid.UUID       `json:"id"`
	TransferID            uuid.UUID       `json:"transfer_id"`
	Status                DisputeStatus   `json:"status"`
	Category              DisputeCategory `json:"category"`
	Reason                string          `json:"reason"`
	ResolutionNote        string          `json:"resolution_note"`
	ScamType              *string         `json:"scam_type"`
	SlaDueAt              *time.Time      `json:"sla_due_at"`
	Decision              DisputeDecision `json:"decision"`
	ReimbursedAmountMinor *int64          `json:"reimbursed_amount_minor"`
	VulnerableFlag        bool            `json:"vulnerable_flag"`
	RecallStatus          RecallStatus    `json:"recall_status"`
	RecallReason          string          `json:"recall_reason"`
	Currency              string          `json:"currency"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

func (q *Queries) ListDisputesForRaiser(ctx context.Context, arg ListDisputesForRaiserParams) ([]ListDisputesForRaiserRow, error) {
	rows, err := q.db.Query(ctx, listDisputesForRaiser, arg.Raiser, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputesForRaiserRow
	for rows.Next() {
		var i ListDisputesForRaiserRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Status,
			&i.Category,
			&i.Reason,
			&i.ResolutionNote,
			&i.ScamType,
			&i.SlaDueAt,
			&i.Decision,
			&i.ReimbursedAmountMinor,
			&i.VulnerableFlag,
			&i.RecallStatus,
			&i.RecallReason,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseDispute = `-- name: RaiseDispute :one
SELECT raise_dispute(
    $1::uuid,
    $2::uuid,
    $3::dispute_category,
    $4::text,
    $5::scam_type
) AS id
`

type RaiseDisputeParams struct {
	TransferID uuid.UUID       `json:"transfer_id"`
	Raiser     uuid.UUID       `json:"raiser"`
	Category   DisputeCategory `json:"category"`
	Reason     string          `json:"reason"`
	ScamType   *string         `json:"scam_type"`
}

func (q *Queries) RaiseDispute(ctx context.Context, arg RaiseDisputeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, raiseDispute,
		arg.TransferID,
		arg.Raiser,
		arg.Category,
		arg.Reason,
		arg.ScamType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveDispute = `-- name: ResolveDispute :one
SELECT resolve_dispute(
    $1::uuid,
    $2::uuid,
    $3::dispute_status,
    $4::text
) AS status
`

type ResolveDisputeParams struct {
	DisputeID uuid.UUID     `json:"dispute_id"`
	Resolver  uuid.UUID     `json:"resolver"`
	Status    DisputeStatus `json:"status"`
	Note      string        `json:"note"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (DisputeStatus, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.DisputeID,
		arg.Resolver,
		arg.Status,
		arg.Note,
	)
	var status DisputeStatus
	err := row.Scan(&status)
	return status, err
}

const setDisputeRecall = `-- name: SetDisputeRecall :one
SELECT set_dispute_recall($1::uuid, $2::uuid,
    $3::recall_status, $4::text) AS recall_status
`

type SetDisputeRecallParams struct {
	DisputeID uuid.UUID    `json:"dispute_id"`
	Actor     uuid.UUID    `json:"actor"`
	Status    RecallStatus `json:"status"`
	Reason    string       `json:"reason"`
}

func (q *Queries) SetDisputeRecall(ctx context.Context, arg SetDisputeRecallParams) (RecallStatus, error) {
	row := q.db.QueryRow(ctx, setDisputeRecall,
		arg.DisputeID,
		arg.Actor,
		arg.Status,
		arg.Reason,
	)
	var recall_status RecallStatus
	err := row.Scan(&recall_status)
	return recall_status, err
}
