// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countMyUnreadEvents = `-- name: CountMyUnreadEvents :one
SELECT COUNT(*)::int AS unread FROM events
WHERE user_id = $1::uuid AND read_at IS NULL
`

func (q *Queries) CountMyUnreadEvents(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMyUnreadEvents, userID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}

const listMyEvents = `-- name: ListMyEvents :many

SELECT id, user_id, type, title, body, related_transfer_id, related_account_id,
       data, read_at, created_at
FROM events
WHERE user_id = $1::uuid
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz,
                              COALESCE($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff')))
  AND ($4::event_type IS NULL OR type = $4::event_type)
  AND (NOT $5::boolean OR read_at IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $6::int
`

type ListMyEventsParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	Cursor     *time.Time    `json:"cursor"`
	CursorID   *uuid.UUID    `json:"cursor_id"`
	Type       NullEventType `json:"type"`
	UnreadOnly bool          `json:"unread_only"`
	PageLimit  int32         `json:"page_limit"`
}

// Notification feed (events, 00008). Bare-array keyset list, matching the
// ledger/transfers convention (cursor = last row's created_at + id).
func (q *Queries) ListMyEvents(ctx context.Context, arg ListMyEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listMyEvents,
		arg.UserID,
		arg.Cursor,
		arg.CursorID,
		arg.Type,
		arg.UnreadOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedTransferID,
			&i.RelatedAccountID,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsRead = `-- name: MarkEventsRead :one
SELECT mark_events_read($1::uuid,
    $2::timestamptz, $3::uuid) AS marked
`

type MarkEventsReadParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	Cursor   *time.Time `json:"cursor"`
	CursorID *uuid.UUID `json:"cursor_id"`
}

func (q *Queries) MarkEventsRead(ctx context.Context, arg MarkEventsReadParams) (int32, error) {
	row := q.db.QueryRow(ctx, markEventsRead, arg.UserID, arg.Cursor, arg.CursorID)
	var marked int32
	err := row.Scan(&marked)
	return marked, err
}
