// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const listInvitationsByInviter = `-- name: ListInvitationsByInviter :many
SELECT code, created_at, expires_at, consumed_at
FROM invitations
WHERE inviter_id = $1::uuid
ORDER BY created_at DESC
`

type ListInvitationsByInviterRow struct {
	Code       string     `json:"code"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

// Raw rows for the caller's invitations, newest first. Status (pending/consumed/
// expired) is DERIVED in Go from consumed_at/expires_at — not stored.
func (q *Queries) ListInvitationsByInviter(ctx context.Context, inviterID uuid.UUID) ([]ListInvitationsByInviterRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsByInviter, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsByInviterRow
	for rows.Next() {
		var i ListInvitationsByInviterRow
		if err := rows.Scan(
			&i.Code,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
