// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maker_checker.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const approveRequest = `-- name: ApproveRequest :one
SELECT approve_request($1::uuid, $2::uuid) AS transfer_id
`

type ApproveRequestParams struct {
	RequestID uuid.UUID `json:"request_id"`
	Approver  uuid.UUID `json:"approver"`
}

func (q *Queries) ApproveRequest(ctx context.Context, arg ApproveRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, approveRequest, arg.RequestID, arg.Approver)
	var transfer_id uuid.UUID
	err := row.Scan(&transfer_id)
	return transfer_id, err
}

const countPendingApprovals = `-- name: CountPendingApprovals :one
SELECT count(*)::int FROM admin_actions
WHERE action = 'approval_request' AND approved_by IS NULL
`

func (q *Queries) CountPendingApprovals(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingApprovals)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :one
SELECT create_approval_request(
    $1::uuid,
    $2::uuid,
    $3::jsonb
) AS id
`

type CreateApprovalRequestParams struct {
	Maker      uuid.UUID `json:"maker"`
	TransferID uuid.UUID `json:"transfer_id"`
	Detail     []byte    `json:"detail"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest, arg.Maker, arg.TransferID, arg.Detail)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT aa.id,
       aa.created_at,
       aa.detail,
       COALESCE(u.username::text, '')::text  AS maker,
       t.amount_minor,
       COALESCE(ca.iban, ca.system_code, '') AS credit_iban,
       COALESCE(da.iban, da.system_code, '') AS debit_iban
FROM admin_actions aa
JOIN transfers t  ON t.id  = aa.target_id
LEFT JOIN users u ON u.id  = aa.actor_user_id
JOIN accounts da  ON da.id = t.debit_account_id
JOIN accounts ca  ON ca.id = t.credit_account_id
WHERE aa.action = 'approval_request' AND aa.approved_by IS NULL AND t.status = 'pending'
ORDER BY aa.created_at DESC
LIMIT $1::int
`

type ListPendingApprovalsRow struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Detail      []byte    `json:"detail"`
	Maker       string    `json:"maker"`
	AmountMinor int64     `json:"amount_minor"`
	CreditIban  string    `json:"credit_iban"`
	DebitIban   string    `json:"debit_iban"`
}

func (q *Queries) ListPendingApprovals(ctx context.Context, pageLimit int32) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsRow
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Detail,
			&i.Maker,
			&i.AmountMinor,
			&i.CreditIban,
			&i.DebitIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRequest = `-- name: RejectRequest :one
SELECT reject_request($1::uuid, $2::uuid, $3::text) AS transfer_id
`

type RejectRequestParams struct {
	RequestID uuid.UUID `json:"request_id"`
	Approver  uuid.UUID `json:"approver"`
	Reason    string    `json:"reason"`
}

func (q *Queries) RejectRequest(ctx context.Context, arg RejectRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rejectRequest, arg.RequestID, arg.Approver, arg.Reason)
	var transfer_id uuid.UUID
	err := row.Scan(&transfer_id)
	return transfer_id, err
}

const requestDeposit = `-- name: RequestDeposit :one
SELECT request_deposit(
    $1::text,
    $2::uuid,
    $3::bigint,
    $4::text
) AS transfer_id
`

type RequestDepositParams struct {
	IdempotencyKey string    `json:"idempotency_key"`
	AccountID      uuid.UUID `json:"account_id"`
	AmountMinor    int64     `json:"amount_minor"`
	Description    string    `json:"description"`
}

func (q *Queries) RequestDeposit(ctx context.Context, arg RequestDepositParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, requestDeposit,
		arg.IdempotencyKey,
		arg.AccountID,
		arg.AmountMinor,
		arg.Description,
	)
	var transfer_id uuid.UUID
	err := row.Scan(&transfer_id)
	return transfer_id, err
}

const requestWithdrawal = `-- name: RequestWithdrawal :one
SELECT request_withdrawal(
    $1::text,
    $2::uuid,
    $3::bigint,
    $4::text
) AS transfer_id
`

type RequestWithdrawalParams struct {
	IdempotencyKey string    `json:"idempotency_key"`
	AccountID      uuid.UUID `json:"account_id"`
	AmountMinor    int64     `json:"amount_minor"`
	Description    string    `json:"description"`
}

func (q *Queries) RequestWithdrawal(ctx context.Context, arg RequestWithdrawalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, requestWithdrawal,
		arg.IdempotencyKey,
		arg.AccountID,
		arg.AmountMinor,
		arg.Description,
	)
	var transfer_id uuid.UUID
	err := row.Scan(&transfer_id)
	return transfer_id, err
}
