// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
)

type AccountKind string

const (
	AccountKindCustomer AccountKind = "customer"
	AccountKindSystem   AccountKind = "system"
)

func (e *AccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountKind(s)
	case string:
		*e = AccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountKind: %T", src)
	}
	return nil
}

type NullAccountKind struct {
	AccountKind AccountKind `json:"account_kind"`
	Valid       bool        `json:"valid"` // Valid is true if AccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.AccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountKind), nil
}

type AccountStatus string

const (
	AccountStatusActive AccountStatus = "active"
	AccountStatusFrozen AccountStatus = "frozen"
	AccountStatusClosed AccountStatus = "closed"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type EntryDirection string

const (
	EntryDirectionDebit  EntryDirection = "debit"
	EntryDirectionCredit EntryDirection = "credit"
)

func (e *EntryDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryDirection(s)
	case string:
		*e = EntryDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryDirection: %T", src)
	}
	return nil
}

type NullEntryDirection struct {
	EntryDirection EntryDirection `json:"entry_direction"`
	Valid          bool           `json:"valid"` // Valid is true if EntryDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryDirection) Scan(value interface{}) error {
	if value == nil {
		ns.EntryDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryDirection), nil
}

type HoldStatus string

const (
	HoldStatusActive   HoldStatus = "active"
	HoldStatusCaptured HoldStatus = "captured"
	HoldStatusReleased HoldStatus = "released"
	HoldStatusExpired  HoldStatus = "expired"
)

func (e *HoldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HoldStatus(s)
	case string:
		*e = HoldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HoldStatus: %T", src)
	}
	return nil
}

type NullHoldStatus struct {
	HoldStatus HoldStatus `json:"hold_status"`
	Valid      bool       `json:"valid"` // Valid is true if HoldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHoldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HoldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HoldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHoldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HoldStatus), nil
}

type IkStatus string

const (
	IkStatusInProgress IkStatus = "in_progress"
	IkStatusCompleted  IkStatus = "completed"
)

func (e *IkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IkStatus(s)
	case string:
		*e = IkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IkStatus: %T", src)
	}
	return nil
}

type NullIkStatus struct {
	IkStatus IkStatus `json:"ik_status"`
	Valid    bool     `json:"valid"` // Valid is true if IkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IkStatus), nil
}

type TransferKind string

const (
	TransferKindTransfer   TransferKind = "transfer"
	TransferKindDeposit    TransferKind = "deposit"
	TransferKindWithdrawal TransferKind = "withdrawal"
	TransferKindReversal   TransferKind = "reversal"
	TransferKindFee        TransferKind = "fee"
	TransferKindAdjustment TransferKind = "adjustment"
)

func (e *TransferKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferKind(s)
	case string:
		*e = TransferKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferKind: %T", src)
	}
	return nil
}

type NullTransferKind struct {
	TransferKind TransferKind `json:"transfer_kind"`
	Valid        bool         `json:"valid"` // Valid is true if TransferKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransferKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferKind), nil
}

type TransferStatus string

const (
	TransferStatusPending  TransferStatus = "pending"
	TransferStatusPosted   TransferStatus = "posted"
	TransferStatusFailed   TransferStatus = "failed"
	TransferStatusCanceled TransferStatus = "canceled"
	TransferStatusReversed TransferStatus = "reversed"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus `json:"transfer_status"`
	Valid          bool           `json:"valid"` // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleOperator UserRole = "operator"
	UserRoleAdmin    UserRole = "admin"
	UserRoleAuditor  UserRole = "auditor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive UserStatus = "active"
	UserStatusLocked UserStatus = "locked"
	UserStatusClosed UserStatus = "closed"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Account struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             *uuid.UUID    `json:"user_id"`
	Kind               AccountKind   `json:"kind"`
	SystemCode         *string       `json:"system_code"`
	Iban               *string       `json:"iban"`
	PinHash            *string       `json:"pin_hash"`
	Currency           string        `json:"currency"`
	BalanceMinor       int64         `json:"balance_minor"`
	TransferLimitMinor int64         `json:"transfer_limit_minor"`
	IsDefault          bool          `json:"is_default"`
	Status             AccountStatus `json:"status"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type AdminAction struct {
	ID          uuid.UUID  `json:"id"`
	ActorUserID uuid.UUID  `json:"actor_user_id"`
	Action      string     `json:"action"`
	TargetID    *uuid.UUID `json:"target_id"`
	Detail      []byte     `json:"detail"`
	ApprovedBy  *uuid.UUID `json:"approved_by"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Beneficiary struct {
	ID              uuid.UUID `json:"id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	Label           string    `json:"label"`
	CreditAccountID uuid.UUID `json:"credit_account_id"`
	Iban            string    `json:"iban"`
	OwnerNameMasked string    `json:"owner_name_masked"`
	CreatedAt       time.Time `json:"created_at"`
}

type EnrichedLedger struct {
	ID                     uuid.UUID      `json:"id"`
	TransferID             uuid.UUID      `json:"transfer_id"`
	AccountID              uuid.UUID      `json:"account_id"`
	AccountIban            *string        `json:"account_iban"`
	AccountSystemCode      *string        `json:"account_system_code"`
	AccountOwner           *string        `json:"account_owner"`
	Direction              EntryDirection `json:"direction"`
	AmountMinor            int64          `json:"amount_minor"`
	SignedAmount           *int64         `json:"signed_amount"`
	BalanceAfter           int64          `json:"balance_after"`
	Currency               string         `json:"currency"`
	PostedAt               time.Time      `json:"posted_at"`
	TransferKind           TransferKind   `json:"transfer_kind"`
	TransferStatus         TransferStatus `json:"transfer_status"`
	Description            string         `json:"description"`
	ReversesID             *uuid.UUID     `json:"reverses_id"`
	CounterpartyAccountID  uuid.UUID      `json:"counterparty_account_id"`
	CounterpartyIban       *string        `json:"counterparty_iban"`
	CounterpartySystemCode *string        `json:"counterparty_system_code"`
	CounterpartyOwner      *string        `json:"counterparty_owner"`
}

type Hold struct {
	ID          uuid.UUID  `json:"id"`
	AccountID   uuid.UUID  `json:"account_id"`
	TransferID  *uuid.UUID `json:"transfer_id"`
	AmountMinor int64      `json:"amount_minor"`
	Status      HoldStatus `json:"status"`
	ExpiresAt   time.Time  `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	ReleasedAt  *time.Time `json:"released_at"`
}

type IdempotencyKey struct {
	Key         string     `json:"key"`
	Scope       string     `json:"scope"`
	RequestHash string     `json:"request_hash"`
	Status      IkStatus   `json:"status"`
	TransferID  *uuid.UUID `json:"transfer_id"`
	Response    []byte     `json:"response"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   time.Time  `json:"expires_at"`
}

type LedgerEntry struct {
	ID           uuid.UUID      `json:"id"`
	TransferID   uuid.UUID      `json:"transfer_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	Direction    EntryDirection `json:"direction"`
	AmountMinor  int64          `json:"amount_minor"`
	SignedAmount *int64         `json:"signed_amount"`
	BalanceAfter int64          `json:"balance_after"`
	Currency     string         `json:"currency"`
	PostedAt     time.Time      `json:"posted_at"`
}

type RefreshToken struct {
	ID            string     `json:"id"`
	FamilyID      uuid.UUID  `json:"family_id"`
	UserID        uuid.UUID  `json:"user_id"`
	ParentID      *string    `json:"parent_id"`
	IssuedAt      time.Time  `json:"issued_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	RotatedAt     *time.Time `json:"rotated_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason *string    `json:"revoked_reason"`
	UserAgent     *string    `json:"user_agent"`
	Ip            *string    `json:"ip"`
}

type Session struct {
	ID         string    `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	UserAgent  *string   `json:"user_agent"`
	Ip         *string   `json:"ip"`
}

type Transfer struct {
	ID              uuid.UUID      `json:"id"`
	DebitAccountID  uuid.UUID      `json:"debit_account_id"`
	CreditAccountID uuid.UUID      `json:"credit_account_id"`
	AmountMinor     int64          `json:"amount_minor"`
	Currency        string         `json:"currency"`
	Status          TransferStatus `json:"status"`
	Kind            TransferKind   `json:"kind"`
	ReversesID      *uuid.UUID     `json:"reverses_id"`
	Description     string         `json:"description"`
	IdempotencyKey  *string        `json:"idempotency_key"`
	FailureReason   *string        `json:"failure_reason"`
	RequestedAt     time.Time      `json:"requested_at"`
	PostedAt        *time.Time     `json:"posted_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	Email        *string    `json:"email"`
	PhoneNumber  *string    `json:"phone_number"`
	Role         UserRole   `json:"role"`
	Status       UserStatus `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
