// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
)

type AccountKind string

const (
	AccountKindCustomer AccountKind = "customer"
	AccountKindSystem   AccountKind = "system"
)

func (e *AccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountKind(s)
	case string:
		*e = AccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountKind: %T", src)
	}
	return nil
}

type NullAccountKind struct {
	AccountKind AccountKind `json:"account_kind"`
	Valid       bool        `json:"valid"` // Valid is true if AccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.AccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountKind), nil
}

type AccountStatus string

const (
	AccountStatusActive AccountStatus = "active"
	AccountStatusFrozen AccountStatus = "frozen"
	AccountStatusClosed AccountStatus = "closed"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type DisputeCategory string

const (
	DisputeCategoryUnrecognised DisputeCategory = "unrecognised"
	DisputeCategoryFraud        DisputeCategory = "fraud"
	DisputeCategoryWrongAmount  DisputeCategory = "wrong_amount"
	DisputeCategoryDuplicate    DisputeCategory = "duplicate"
	DisputeCategoryOther        DisputeCategory = "other"
)

func (e *DisputeCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeCategory(s)
	case string:
		*e = DisputeCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeCategory: %T", src)
	}
	return nil
}

type NullDisputeCategory struct {
	DisputeCategory DisputeCategory `json:"dispute_category"`
	Valid           bool            `json:"valid"` // Valid is true if DisputeCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeCategory) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeCategory), nil
}

type DisputeDecision string

const (
	DisputeDecisionPending             DisputeDecision = "pending"
	DisputeDecisionReimbursed          DisputeDecision = "reimbursed"
	DisputeDecisionPartiallyReimbursed DisputeDecision = "partially_reimbursed"
	DisputeDecisionDeclined            DisputeDecision = "declined"
)

func (e *DisputeDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeDecision(s)
	case string:
		*e = DisputeDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeDecision: %T", src)
	}
	return nil
}

type NullDisputeDecision struct {
	DisputeDecision DisputeDecision `json:"dispute_decision"`
	Valid           bool            `json:"valid"` // Valid is true if DisputeDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeDecision) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeDecision), nil
}

type DisputeStatus string

const (
	DisputeStatusOpen        DisputeStatus = "open"
	DisputeStatusUnderReview DisputeStatus = "under_review"
	DisputeStatusResolved    DisputeStatus = "resolved"
	DisputeStatusRejected    DisputeStatus = "rejected"
)

func (e *DisputeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeStatus(s)
	case string:
		*e = DisputeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeStatus: %T", src)
	}
	return nil
}

type NullDisputeStatus struct {
	DisputeStatus DisputeStatus `json:"dispute_status"`
	Valid         bool          `json:"valid"` // Valid is true if DisputeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeStatus), nil
}

type EntryDirection string

const (
	EntryDirectionDebit  EntryDirection = "debit"
	EntryDirectionCredit EntryDirection = "credit"
)

func (e *EntryDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryDirection(s)
	case string:
		*e = EntryDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryDirection: %T", src)
	}
	return nil
}

type NullEntryDirection struct {
	EntryDirection EntryDirection `json:"entry_direction"`
	Valid          bool           `json:"valid"` // Valid is true if EntryDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryDirection) Scan(value interface{}) error {
	if value == nil {
		ns.EntryDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryDirection), nil
}

type EventType string

const (
	EventTypeTransferposted  EventType = "transfer.posted"
	EventTypePaymentincoming EventType = "payment.incoming"
	EventTypeDevicenew       EventType = "device.new"
	EventTypeDisputeupdated  EventType = "dispute.updated"
	EventTypeTransferheld    EventType = "transfer.held"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type HoldStatus string

const (
	HoldStatusActive   HoldStatus = "active"
	HoldStatusCaptured HoldStatus = "captured"
	HoldStatusReleased HoldStatus = "released"
	HoldStatusExpired  HoldStatus = "expired"
)

func (e *HoldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HoldStatus(s)
	case string:
		*e = HoldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HoldStatus: %T", src)
	}
	return nil
}

type NullHoldStatus struct {
	HoldStatus HoldStatus `json:"hold_status"`
	Valid      bool       `json:"valid"` // Valid is true if HoldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHoldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HoldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HoldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHoldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HoldStatus), nil
}

type IkStatus string

const (
	IkStatusInProgress IkStatus = "in_progress"
	IkStatusCompleted  IkStatus = "completed"
)

func (e *IkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IkStatus(s)
	case string:
		*e = IkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IkStatus: %T", src)
	}
	return nil
}

type NullIkStatus struct {
	IkStatus IkStatus `json:"ik_status"`
	Valid    bool     `json:"valid"` // Valid is true if IkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IkStatus), nil
}

type MfaKind string

const (
	MfaKindTotp     MfaKind = "totp"
	MfaKindWebauthn MfaKind = "webauthn"
)

func (e *MfaKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaKind(s)
	case string:
		*e = MfaKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaKind: %T", src)
	}
	return nil
}

type NullMfaKind struct {
	MfaKind MfaKind `json:"mfa_kind"`
	Valid   bool    `json:"valid"` // Valid is true if MfaKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaKind) Scan(value interface{}) error {
	if value == nil {
		ns.MfaKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaKind), nil
}

type OnboardingStatus string

const (
	OnboardingStatusPendingVerification OnboardingStatus = "pending_verification"
	OnboardingStatusVerified            OnboardingStatus = "verified"
	OnboardingStatusActive              OnboardingStatus = "active"
	OnboardingStatusRejected            OnboardingStatus = "rejected"
)

func (e *OnboardingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingStatus(s)
	case string:
		*e = OnboardingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingStatus: %T", src)
	}
	return nil
}

type NullOnboardingStatus struct {
	OnboardingStatus OnboardingStatus `json:"onboarding_status"`
	Valid            bool             `json:"valid"` // Valid is true if OnboardingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingStatus), nil
}

type RecallStatus string

const (
	RecallStatusNone          RecallStatus = "none"
	RecallStatusRequested     RecallStatus = "requested"
	RecallStatusFundsReturned RecallStatus = "funds_returned"
	RecallStatusRefused       RecallStatus = "refused"
)

func (e *RecallStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecallStatus(s)
	case string:
		*e = RecallStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecallStatus: %T", src)
	}
	return nil
}

type NullRecallStatus struct {
	RecallStatus RecallStatus `json:"recall_status"`
	Valid        bool         `json:"valid"` // Valid is true if RecallStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecallStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecallStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecallStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecallStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecallStatus), nil
}

type ScamType string

const (
	ScamTypeImpersonation ScamType = "impersonation"
	ScamTypePurchase      ScamType = "purchase"
	ScamTypeInvestment    ScamType = "investment"
	ScamTypeRomance       ScamType = "romance"
	ScamTypeInvoice       ScamType = "invoice"
	ScamTypeAdvanceFee    ScamType = "advance_fee"
	ScamTypeOther         ScamType = "other"
)

func (e *ScamType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScamType(s)
	case string:
		*e = ScamType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScamType: %T", src)
	}
	return nil
}

type NullScamType struct {
	ScamType ScamType `json:"scam_type"`
	Valid    bool     `json:"valid"` // Valid is true if ScamType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScamType) Scan(value interface{}) error {
	if value == nil {
		ns.ScamType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScamType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScamType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScamType), nil
}

type TransferKind string

const (
	TransferKindTransfer   TransferKind = "transfer"
	TransferKindDeposit    TransferKind = "deposit"
	TransferKindWithdrawal TransferKind = "withdrawal"
	TransferKindReversal   TransferKind = "reversal"
	TransferKindFee        TransferKind = "fee"
	TransferKindAdjustment TransferKind = "adjustment"
)

func (e *TransferKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferKind(s)
	case string:
		*e = TransferKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferKind: %T", src)
	}
	return nil
}

type NullTransferKind struct {
	TransferKind TransferKind `json:"transfer_kind"`
	Valid        bool         `json:"valid"` // Valid is true if TransferKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransferKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferKind), nil
}

type TransferStatus string

const (
	TransferStatusPending     TransferStatus = "pending"
	TransferStatusHeld        TransferStatus = "held"
	TransferStatusUnderReview TransferStatus = "under_review"
	TransferStatusPosted      TransferStatus = "posted"
	TransferStatusFailed      TransferStatus = "failed"
	TransferStatusCanceled    TransferStatus = "canceled"
	TransferStatusReversed    TransferStatus = "reversed"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus `json:"transfer_status"`
	Valid          bool           `json:"valid"` // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleOperator UserRole = "operator"
	UserRoleAdmin    UserRole = "admin"
	UserRoleAuditor  UserRole = "auditor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive UserStatus = "active"
	UserStatusLocked UserStatus = "locked"
	UserStatusClosed UserStatus = "closed"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type VerificationChannel string

const (
	VerificationChannelEmail VerificationChannel = "email"
	VerificationChannelPhone VerificationChannel = "phone"
)

func (e *VerificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationChannel(s)
	case string:
		*e = VerificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationChannel: %T", src)
	}
	return nil
}

type NullVerificationChannel struct {
	VerificationChannel VerificationChannel `json:"verification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if VerificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationChannel), nil
}

type VerificationStatus string

const (
	VerificationStatusPending  VerificationStatus = "pending"
	VerificationStatusVerified VerificationStatus = "verified"
	VerificationStatusExpired  VerificationStatus = "expired"
	VerificationStatusCanceled VerificationStatus = "canceled"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type Account struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             *uuid.UUID    `json:"user_id"`
	Kind               AccountKind   `json:"kind"`
	SystemCode         *string       `json:"system_code"`
	Iban               *string       `json:"iban"`
	PinHash            *string       `json:"pin_hash"`
	Currency           string        `json:"currency"`
	BalanceMinor       int64         `json:"balance_minor"`
	TransferLimitMinor int64         `json:"transfer_limit_minor"`
	IsDefault          bool          `json:"is_default"`
	Status             AccountStatus `json:"status"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
	HeldMinor          int64         `json:"held_minor"`
}

type AdminAction struct {
	ID          uuid.UUID  `json:"id"`
	ActorUserID uuid.UUID  `json:"actor_user_id"`
	Action      string     `json:"action"`
	TargetID    *uuid.UUID `json:"target_id"`
	Detail      []byte     `json:"detail"`
	ApprovedBy  *uuid.UUID `json:"approved_by"`
	CreatedAt   time.Time  `json:"created_at"`
}

type BankSetting struct {
	ID                         bool       `json:"id"`
	MakerCheckerThresholdMinor int64      `json:"maker_checker_threshold_minor"`
	DefaultTransferLimitMinor  int64      `json:"default_transfer_limit_minor"`
	UpdatedAt                  time.Time  `json:"updated_at"`
	UpdatedBy                  *uuid.UUID `json:"updated_by"`
	DefaultPageLimit           int32      `json:"default_page_limit"`
	MaxAccountsPerUser         int32      `json:"max_accounts_per_user"`
	ReimbursementCapMinor      int64      `json:"reimbursement_cap_minor"`
	ReimbursementExcessMinor   int64      `json:"reimbursement_excess_minor"`
}

type Beneficiary struct {
	ID              uuid.UUID `json:"id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	Label           string    `json:"label"`
	CreditAccountID uuid.UUID `json:"credit_account_id"`
	Iban            string    `json:"iban"`
	OwnerNameMasked string    `json:"owner_name_masked"`
	CreatedAt       time.Time `json:"created_at"`
}

type Dispute struct {
	ID                    uuid.UUID       `json:"id"`
	TransferID            uuid.UUID       `json:"transfer_id"`
	RaisedByUserID        uuid.UUID       `json:"raised_by_user_id"`
	Status                DisputeStatus   `json:"status"`
	Category              DisputeCategory `json:"category"`
	Reason                string          `json:"reason"`
	ResolverUserID        *uuid.UUID      `json:"resolver_user_id"`
	ResolutionNote        string          `json:"resolution_note"`
	ScamType              *string         `json:"scam_type"`
	SlaDueAt              *time.Time      `json:"sla_due_at"`
	Decision              DisputeDecision `json:"decision"`
	ReimbursedAmountMinor *int64          `json:"reimbursed_amount_minor"`
	VulnerableFlag        bool            `json:"vulnerable_flag"`
	RecallStatus          RecallStatus    `json:"recall_status"`
	RecallReason          string          `json:"recall_reason"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type EnrichedLedger struct {
	ID                     uuid.UUID      `json:"id"`
	TransferID             uuid.UUID      `json:"transfer_id"`
	AccountID              uuid.UUID      `json:"account_id"`
	AccountIban            *string        `json:"account_iban"`
	AccountSystemCode      *string        `json:"account_system_code"`
	AccountOwner           *string        `json:"account_owner"`
	Direction              EntryDirection `json:"direction"`
	AmountMinor            int64          `json:"amount_minor"`
	SignedAmount           *int64         `json:"signed_amount"`
	BalanceAfter           int64          `json:"balance_after"`
	Currency               string         `json:"currency"`
	PostedAt               time.Time      `json:"posted_at"`
	TransferKind           TransferKind   `json:"transfer_kind"`
	TransferStatus         TransferStatus `json:"transfer_status"`
	Description            string         `json:"description"`
	ReversesID             *uuid.UUID     `json:"reverses_id"`
	CounterpartyAccountID  uuid.UUID      `json:"counterparty_account_id"`
	CounterpartyIban       *string        `json:"counterparty_iban"`
	CounterpartySystemCode *string        `json:"counterparty_system_code"`
	CounterpartyOwner      *string        `json:"counterparty_owner"`
}

type Event struct {
	ID                uuid.UUID  `json:"id"`
	UserID            uuid.UUID  `json:"user_id"`
	Type              EventType  `json:"type"`
	Title             string     `json:"title"`
	Body              string     `json:"body"`
	RelatedTransferID *uuid.UUID `json:"related_transfer_id"`
	RelatedAccountID  *uuid.UUID `json:"related_account_id"`
	Data              []byte     `json:"data"`
	ReadAt            *time.Time `json:"read_at"`
	CreatedAt         time.Time  `json:"created_at"`
}

type GuidedScenario struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	TargetAccountID uuid.UUID  `json:"target_account_id"`
	Reason          string     `json:"reason"`
	Active          bool       `json:"active"`
	TargetUserID    *uuid.UUID `json:"target_user_id"`
	MinAmountMinor  int64      `json:"min_amount_minor"`
	Priority        int32      `json:"priority"`
	CreatedAt       time.Time  `json:"created_at"`
}

type Hold struct {
	ID          uuid.UUID  `json:"id"`
	AccountID   uuid.UUID  `json:"account_id"`
	TransferID  *uuid.UUID `json:"transfer_id"`
	AmountMinor int64      `json:"amount_minor"`
	Status      HoldStatus `json:"status"`
	ExpiresAt   time.Time  `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	ReleasedAt  *time.Time `json:"released_at"`
}

type IdempotencyKey struct {
	OwnerID     uuid.UUID  `json:"owner_id"`
	Key         string     `json:"key"`
	Scope       string     `json:"scope"`
	RequestHash string     `json:"request_hash"`
	Status      IkStatus   `json:"status"`
	TransferID  *uuid.UUID `json:"transfer_id"`
	Response    []byte     `json:"response"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   time.Time  `json:"expires_at"`
}

type Invitation struct {
	ID         uuid.UUID  `json:"id"`
	Code       string     `json:"code"`
	InviterID  uuid.UUID  `json:"inviter_id"`
	InviteeID  *uuid.UUID `json:"invitee_id"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	ConsumedAt *time.Time `json:"consumed_at"`
}

type LedgerEntry struct {
	ID           uuid.UUID      `json:"id"`
	TransferID   uuid.UUID      `json:"transfer_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	Direction    EntryDirection `json:"direction"`
	AmountMinor  int64          `json:"amount_minor"`
	SignedAmount *int64         `json:"signed_amount"`
	BalanceAfter int64          `json:"balance_after"`
	Currency     string         `json:"currency"`
	PostedAt     time.Time      `json:"posted_at"`
}

type MfaAttempt struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Succeeded   bool      `json:"succeeded"`
	Ip          *string   `json:"ip"`
	AttemptedAt time.Time `json:"attempted_at"`
}

type MfaCredential struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Kind        MfaKind    `json:"kind"`
	SecretEnc   []byte     `json:"secret_enc"`
	ConfirmedAt *time.Time `json:"confirmed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type MfaRecoveryCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CodeHash  string     `json:"code_hash"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type RefreshToken struct {
	ID            string     `json:"id"`
	FamilyID      uuid.UUID  `json:"family_id"`
	UserID        uuid.UUID  `json:"user_id"`
	ParentID      *string    `json:"parent_id"`
	IssuedAt      time.Time  `json:"issued_at"`
	ExpiresAt     time.Time  `json:"expires_at"`
	RotatedAt     *time.Time `json:"rotated_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason *string    `json:"revoked_reason"`
	UserAgent     *string    `json:"user_agent"`
	Ip            *string    `json:"ip"`
	DeviceLabel   *string    `json:"device_label"`
}

type Session struct {
	ID         string    `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	UserAgent  *string   `json:"user_agent"`
	Ip         *string   `json:"ip"`
}

type Transfer struct {
	ID              uuid.UUID      `json:"id"`
	DebitAccountID  uuid.UUID      `json:"debit_account_id"`
	CreditAccountID uuid.UUID      `json:"credit_account_id"`
	AmountMinor     int64          `json:"amount_minor"`
	Currency        string         `json:"currency"`
	Status          TransferStatus `json:"status"`
	Kind            TransferKind   `json:"kind"`
	ReversesID      *uuid.UUID     `json:"reverses_id"`
	Description     string         `json:"description"`
	IdempotencyKey  *string        `json:"idempotency_key"`
	Uetr            uuid.UUID      `json:"uetr"`
	EndToEndID      *string        `json:"end_to_end_id"`
	FailureReason   *string        `json:"failure_reason"`
	HoldReason      *string        `json:"hold_reason"`
	HoldExpiresAt   *time.Time     `json:"hold_expires_at"`
	RequestedAt     time.Time      `json:"requested_at"`
	PostedAt        *time.Time     `json:"posted_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID               uuid.UUID        `json:"id"`
	Username         string           `json:"username"`
	PasswordHash     string           `json:"password_hash"`
	FullName         string           `json:"full_name"`
	Email            *string          `json:"email"`
	PhoneNumber      *string          `json:"phone_number"`
	Role             UserRole         `json:"role"`
	Status           UserStatus       `json:"status"`
	OnboardingStatus OnboardingStatus `json:"onboarding_status"`
	EmailVerifiedAt  *time.Time       `json:"email_verified_at"`
	PhoneVerifiedAt  *time.Time       `json:"phone_verified_at"`
	InvitesRemaining int32            `json:"invites_remaining"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

type VerificationChallenge struct {
	ID          uuid.UUID           `json:"id"`
	UserID      uuid.UUID           `json:"user_id"`
	Channel     VerificationChannel `json:"channel"`
	Destination string              `json:"destination"`
	TokenHash   string              `json:"token_hash"`
	CodeHash    string              `json:"code_hash"`
	Status      VerificationStatus  `json:"status"`
	Attempts    int16               `json:"attempts"`
	MaxAttempts int16               `json:"max_attempts"`
	LastSentAt  time.Time           `json:"last_sent_at"`
	ExpiresAt   time.Time           `json:"expires_at"`
	CreatedAt   time.Time           `json:"created_at"`
	VerifiedAt  *time.Time          `json:"verified_at"`
}

type WarningAck struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	Category         string     `json:"category"`
	ReasonCode       string     `json:"reason_code"`
	Acknowledged     bool       `json:"acknowledged"`
	DebitAccountID   *uuid.UUID `json:"debit_account_id"`
	CounterpartyIban string     `json:"counterparty_iban"`
	AmountMinor      *int64     `json:"amount_minor"`
	Device           string     `json:"device"`
	CreatedAt        time.Time  `json:"created_at"`
}

type WarningRule struct {
	ID                uuid.UUID `json:"id"`
	MatchReasonCode   *string   `json:"match_reason_code"`
	MatchMinBand      *string   `json:"match_min_band"`
	Category          string    `json:"category"`
	Headline          string    `json:"headline"`
	Body              string    `json:"body"`
	Severity          string    `json:"severity"`
	Decision          string    `json:"decision"`
	RequiredAck       bool      `json:"required_ack"`
	CoolingOffSeconds int32     `json:"cooling_off_seconds"`
	Priority          int32     `json:"priority"`
	Active            bool      `json:"active"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type WatchlistEntry struct {
	ID        uuid.UUID `json:"id"`
	Pattern   string    `json:"pattern"`
	Reason    string    `json:"reason"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}
