// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const accountOwner = `-- name: AccountOwner :one

SELECT user_id FROM accounts WHERE id = $1
`

// Ownership lookups used by the client-surface (JWT) authorization checks.
func (q *Queries) AccountOwner(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, accountOwner, id)
	var user_id *uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const familyOwnedBy = `-- name: FamilyOwnedBy :one
SELECT EXISTS (
    SELECT 1 FROM refresh_tokens
     WHERE family_id = $1::uuid AND user_id = $2::uuid
) AS owned
`

type FamilyOwnedByParams struct {
	Family uuid.UUID `json:"family"`
	Owner  uuid.UUID `json:"owner"`
}

// True iff the refresh-token family belongs to the caller. Lets DELETE
// /me/sessions/{family_id} return 404 for a non-owned family while staying
// idempotent (204) for the owner's already-revoked family.
func (q *Queries) FamilyOwnedBy(ctx context.Context, arg FamilyOwnedByParams) (bool, error) {
	row := q.db.QueryRow(ctx, familyOwnedBy, arg.Family, arg.Owner)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const transferOwners = `-- name: TransferOwners :one
SELECT da.user_id AS debit_owner,
       ca.user_id AS credit_owner
FROM transfers t
JOIN accounts da ON da.id = t.debit_account_id
JOIN accounts ca ON ca.id = t.credit_account_id
WHERE t.id = $1
`

type TransferOwnersRow struct {
	DebitOwner  *uuid.UUID `json:"debit_owner"`
	CreditOwner *uuid.UUID `json:"credit_owner"`
}

func (q *Queries) TransferOwners(ctx context.Context, id uuid.UUID) (TransferOwnersRow, error) {
	row := q.db.QueryRow(ctx, transferOwners, id)
	var i TransferOwnersRow
	err := row.Scan(&i.DebitOwner, &i.CreditOwner)
	return i, err
}
