// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const challengeByToken = `-- name: ChallengeByToken :one
SELECT user_id, channel, destination, status
FROM verification_challenges WHERE token_hash = $1::text
`

type ChallengeByTokenRow struct {
	UserID      uuid.UUID           `json:"user_id"`
	Channel     VerificationChannel `json:"channel"`
	Destination string              `json:"destination"`
	Status      VerificationStatus  `json:"status"`
}

func (q *Queries) ChallengeByToken(ctx context.Context, tokenHash string) (ChallengeByTokenRow, error) {
	row := q.db.QueryRow(ctx, challengeByToken, tokenHash)
	var i ChallengeByTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.Status,
	)
	return i, err
}

const createVerificationChallenge = `-- name: CreateVerificationChallenge :one

SELECT create_verification_challenge($1::uuid,
    $2::verification_channel, $3::text,
    $4::text, $5::text) AS id
`

type CreateVerificationChallengeParams struct {
	UserID      uuid.UUID           `json:"user_id"`
	Channel     VerificationChannel `json:"channel"`
	Destination string              `json:"destination"`
	TokenHash   string              `json:"token_hash"`
	CodeHash    string              `json:"code_hash"`
}

// Self-registration & contact verification (00011). register_user and
// verify_contact are RETURNS TABLE -> hand-written pgx in internal/db/registration.go.
func (q *Queries) CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVerificationChallenge,
		arg.UserID,
		arg.Channel,
		arg.Destination,
		arg.TokenHash,
		arg.CodeHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
