// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const searchAccounts = `-- name: SearchAccounts :many
SELECT a.id, a.user_id,
       COALESCE(u.full_name, '') AS owner,
       COALESCE(a.iban, '')      AS iban,
       a.status, a.balance_minor,
       account_available(a.id)   AS available_minor,
       a.created_at
FROM accounts a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.kind = 'customer'
  AND ($1::timestamptz IS NULL
       OR (a.created_at, a.id) < ($1::timestamptz, $2::uuid))
  AND (
      $3::text IS NULL OR $3::text = ''
   OR a.iban::text ILIKE '%' || $3 || '%'
   OR u.full_name ILIKE '%' || $3 || '%'
   OR word_similarity($3::text, COALESCE(a.iban::text, '')) > 0.3
   OR word_similarity($3::text, COALESCE(u.full_name, '')) > 0.3
  )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4::int
`

type SearchAccountsParams struct {
	Cursor    *time.Time `json:"cursor"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Q         *string    `json:"q"`
	PageLimit int32      `json:"page_limit"`
}

type SearchAccountsRow struct {
	ID             uuid.UUID     `json:"id"`
	UserID         *uuid.UUID    `json:"user_id"`
	Owner          string        `json:"owner"`
	Iban           string        `json:"iban"`
	Status         AccountStatus `json:"status"`
	BalanceMinor   int64         `json:"balance_minor"`
	AvailableMinor int64         `json:"available_minor"`
	CreatedAt      time.Time     `json:"created_at"`
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]SearchAccountsRow, error) {
	rows, err := q.db.Query(ctx, searchAccounts,
		arg.Cursor,
		arg.CursorID,
		arg.Q,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAccountsRow
	for rows.Next() {
		var i SearchAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Owner,
			&i.Iban,
			&i.Status,
			&i.BalanceMinor,
			&i.AvailableMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransfers = `-- name: SearchTransfers :many
SELECT t.id,
       COALESCE(da.iban, da.system_code, '') AS debit,
       COALESCE(ca.iban, ca.system_code, '') AS credit,
       t.kind, t.status, t.amount_minor, t.description, t.requested_at
FROM transfers t
JOIN accounts da ON da.id = t.debit_account_id
JOIN accounts ca ON ca.id = t.credit_account_id
WHERE ($1::timestamptz IS NULL
       OR (t.requested_at, t.id) < ($1::timestamptz, $2::uuid))
  AND (
      $3::text IS NULL OR $3::text = ''
   OR t.description ILIKE '%' || $3 || '%'
   OR COALESCE(da.iban::text, '') ILIKE '%' || $3 || '%'
   OR COALESCE(ca.iban::text, '') ILIKE '%' || $3 || '%'
   OR word_similarity($3::text, t.description) > 0.3
  )
ORDER BY t.requested_at DESC, t.id DESC
LIMIT $4::int
`

type SearchTransfersParams struct {
	Cursor    *time.Time `json:"cursor"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Q         *string    `json:"q"`
	PageLimit int32      `json:"page_limit"`
}

type SearchTransfersRow struct {
	ID          uuid.UUID      `json:"id"`
	Debit       string         `json:"debit"`
	Credit      string         `json:"credit"`
	Kind        TransferKind   `json:"kind"`
	Status      TransferStatus `json:"status"`
	AmountMinor int64          `json:"amount_minor"`
	Description string         `json:"description"`
	RequestedAt time.Time      `json:"requested_at"`
}

func (q *Queries) SearchTransfers(ctx context.Context, arg SearchTransfersParams) ([]SearchTransfersRow, error) {
	rows, err := q.db.Query(ctx, searchTransfers,
		arg.Cursor,
		arg.CursorID,
		arg.Q,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransfersRow
	for rows.Next() {
		var i SearchTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Debit,
			&i.Credit,
			&i.Kind,
			&i.Status,
			&i.AmountMinor,
			&i.Description,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many

SELECT id, username, full_name, email, phone_number, role, status, created_at, updated_at
FROM users
WHERE ($1::timestamptz IS NULL
       OR (created_at, id) < ($1::timestamptz, $2::uuid))
  AND (
      $3::text IS NULL OR $3::text = ''
   OR username::text ILIKE '%' || $3 || '%'
   OR full_name ILIKE '%' || $3 || '%'
   OR COALESCE(email::text, '') ILIKE '%' || $3 || '%'
   OR word_similarity($3::text, username::text) > 0.3
   OR word_similarity($3::text, full_name) > 0.3
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type SearchUsersParams struct {
	Cursor    *time.Time `json:"cursor"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Q         *string    `json:"q"`
	PageLimit int32      `json:"page_limit"`
}

type SearchUsersRow struct {
	ID          uuid.UUID  `json:"id"`
	Username    string     `json:"username"`
	FullName    string     `json:"full_name"`
	Email       *string    `json:"email"`
	PhoneNumber *string    `json:"phone_number"`
	Role        UserRole   `json:"role"`
	Status      UserStatus `json:"status"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// Unified list+search queries. When q is NULL/” they return everything (the
// plain list); otherwise q is a FILTER only (substring ILIKE OR trigram
// word_similarity > 0.3). Ordering is a stable (created_at, id) keyset so the
// list keyset-paginates correctly — a similarity rank can't be keyset-paginated
// (and recomputing word_similarity per row to rank was a known perf drag).
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Cursor,
		arg.CursorID,
		arg.Q,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
