// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getBankSettings = `-- name: GetBankSettings :one
SELECT maker_checker_threshold_minor, default_transfer_limit_minor, default_page_limit, updated_at, updated_by
FROM bank_settings WHERE id
`

type GetBankSettingsRow struct {
	MakerCheckerThresholdMinor int64      `json:"maker_checker_threshold_minor"`
	DefaultTransferLimitMinor  int64      `json:"default_transfer_limit_minor"`
	DefaultPageLimit           int32      `json:"default_page_limit"`
	UpdatedAt                  time.Time  `json:"updated_at"`
	UpdatedBy                  *uuid.UUID `json:"updated_by"`
}

func (q *Queries) GetBankSettings(ctx context.Context) (GetBankSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBankSettings)
	var i GetBankSettingsRow
	err := row.Scan(
		&i.MakerCheckerThresholdMinor,
		&i.DefaultTransferLimitMinor,
		&i.DefaultPageLimit,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateBankSettings = `-- name: UpdateBankSettings :exec
SELECT update_bank_settings(
    $1::bigint,
    $2::bigint,
    $3::int,
    $4::uuid
)
`

type UpdateBankSettingsParams struct {
	ThresholdMinor    int64     `json:"threshold_minor"`
	DefaultLimitMinor int64     `json:"default_limit_minor"`
	PageLimit         int32     `json:"page_limit"`
	Actor             uuid.UUID `json:"actor"`
}

func (q *Queries) UpdateBankSettings(ctx context.Context, arg UpdateBankSettingsParams) error {
	_, err := q.db.Exec(ctx, updateBankSettings,
		arg.ThresholdMinor,
		arg.DefaultLimitMinor,
		arg.PageLimit,
		arg.Actor,
	)
	return err
}
