// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const cancelTransfer = `-- name: CancelTransfer :one
SELECT cancel_transfer($1::uuid, $2::text) AS status
`

type CancelTransferParams struct {
	ID     uuid.UUID `json:"id"`
	Reason string    `json:"reason"`
}

func (q *Queries) CancelTransfer(ctx context.Context, arg CancelTransferParams) (TransferStatus, error) {
	row := q.db.QueryRow(ctx, cancelTransfer, arg.ID, arg.Reason)
	var status TransferStatus
	err := row.Scan(&status)
	return status, err
}

const getAccountLedger = `-- name: GetAccountLedger :many
SELECT id, transfer_id, account_id, account_iban, direction, amount_minor, signed_amount,
       balance_after, currency, posted_at, transfer_kind, transfer_status, description,
       counterparty_iban, counterparty_owner
FROM enriched_ledger
WHERE account_id = $1::uuid
  AND posted_at < COALESCE($2::timestamptz, now())
ORDER BY posted_at DESC, id DESC
LIMIT $3::int
`

type GetAccountLedgerParams struct {
	AccountID uuid.UUID  `json:"account_id"`
	Cursor    *time.Time `json:"cursor"`
	PageLimit int32      `json:"page_limit"`
}

type GetAccountLedgerRow struct {
	ID                uuid.UUID      `json:"id"`
	TransferID        uuid.UUID      `json:"transfer_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	AccountIban       *string        `json:"account_iban"`
	Direction         EntryDirection `json:"direction"`
	AmountMinor       int64          `json:"amount_minor"`
	SignedAmount      *int64         `json:"signed_amount"`
	BalanceAfter      int64          `json:"balance_after"`
	Currency          string         `json:"currency"`
	PostedAt          time.Time      `json:"posted_at"`
	TransferKind      TransferKind   `json:"transfer_kind"`
	TransferStatus    TransferStatus `json:"transfer_status"`
	Description       string         `json:"description"`
	CounterpartyIban  *string        `json:"counterparty_iban"`
	CounterpartyOwner *string        `json:"counterparty_owner"`
}

func (q *Queries) GetAccountLedger(ctx context.Context, arg GetAccountLedgerParams) ([]GetAccountLedgerRow, error) {
	rows, err := q.db.Query(ctx, getAccountLedger, arg.AccountID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountLedgerRow
	for rows.Next() {
		var i GetAccountLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.AccountID,
			&i.AccountIban,
			&i.Direction,
			&i.AmountMinor,
			&i.SignedAmount,
			&i.BalanceAfter,
			&i.Currency,
			&i.PostedAt,
			&i.TransferKind,
			&i.TransferStatus,
			&i.Description,
			&i.CounterpartyIban,
			&i.CounterpartyOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, debit_account_id, credit_account_id, amount_minor, currency, status, kind,
       reverses_id, description, failure_reason, requested_at, posted_at, created_at, updated_at
FROM transfers WHERE id = $1::uuid
`

type GetTransferRow struct {
	ID              uuid.UUID      `json:"id"`
	DebitAccountID  uuid.UUID      `json:"debit_account_id"`
	CreditAccountID uuid.UUID      `json:"credit_account_id"`
	AmountMinor     int64          `json:"amount_minor"`
	Currency        string         `json:"currency"`
	Status          TransferStatus `json:"status"`
	Kind            TransferKind   `json:"kind"`
	ReversesID      *uuid.UUID     `json:"reverses_id"`
	Description     string         `json:"description"`
	FailureReason   *string        `json:"failure_reason"`
	RequestedAt     time.Time      `json:"requested_at"`
	PostedAt        *time.Time     `json:"posted_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetTransfer(ctx context.Context, id uuid.UUID) (GetTransferRow, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i GetTransferRow
	err := row.Scan(
		&i.ID,
		&i.DebitAccountID,
		&i.CreditAccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Kind,
		&i.ReversesID,
		&i.Description,
		&i.FailureReason,
		&i.RequestedAt,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTransfers = `-- name: ListPendingTransfers :many
SELECT id, debit_account_id, credit_account_id, amount_minor, currency, kind, description, requested_at
FROM transfers
WHERE status = 'pending'
  AND requested_at < COALESCE($1::timestamptz, now())
ORDER BY requested_at DESC
LIMIT $2::int
`

type ListPendingTransfersParams struct {
	Cursor    *time.Time `json:"cursor"`
	PageLimit int32      `json:"page_limit"`
}

type ListPendingTransfersRow struct {
	ID              uuid.UUID    `json:"id"`
	DebitAccountID  uuid.UUID    `json:"debit_account_id"`
	CreditAccountID uuid.UUID    `json:"credit_account_id"`
	AmountMinor     int64        `json:"amount_minor"`
	Currency        string       `json:"currency"`
	Kind            TransferKind `json:"kind"`
	Description     string       `json:"description"`
	RequestedAt     time.Time    `json:"requested_at"`
}

func (q *Queries) ListPendingTransfers(ctx context.Context, arg ListPendingTransfersParams) ([]ListPendingTransfersRow, error) {
	rows, err := q.db.Query(ctx, listPendingTransfers, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTransfersRow
	for rows.Next() {
		var i ListPendingTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.DebitAccountID,
			&i.CreditAccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.Kind,
			&i.Description,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postTransfer = `-- name: PostTransfer :one

SELECT post_transfer($1::uuid) AS status
`

// NOTE: transfer() and request_transfer() return a TABLE; sqlc cannot expand
// set-returning function columns, so those calls live in internal/db/bank.go
// (hand-written pgx). Everything below is plain sqlc.
func (q *Queries) PostTransfer(ctx context.Context, id uuid.UUID) (TransferStatus, error) {
	row := q.db.QueryRow(ctx, postTransfer, id)
	var status TransferStatus
	err := row.Scan(&status)
	return status, err
}

const reverseTransfer = `-- name: ReverseTransfer :one
SELECT reverse_transfer(
    $1::uuid,
    $2::text,
    $3::text
) AS reversal_id
`

type ReverseTransferParams struct {
	ID             uuid.UUID `json:"id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Reason         string    `json:"reason"`
}

func (q *Queries) ReverseTransfer(ctx context.Context, arg ReverseTransferParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, reverseTransfer, arg.ID, arg.IdempotencyKey, arg.Reason)
	var reversal_id uuid.UUID
	err := row.Scan(&reversal_id)
	return reversal_id, err
}
