// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
SELECT create_user(
    $1::citext,
    $2::text,
    $3::text,
    $4::citext,
    $5::varchar,
    $6::user_role
) AS id
`

type CreateUserParams struct {
	Username    string   `json:"username"`
	Password    string   `json:"password"`
	FullName    string   `json:"full_name"`
	Email       *string  `json:"email"`
	PhoneNumber *string  `json:"phone_number"`
	Role        UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.Role,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name, email, phone_number, role, status, onboarding_status, invites_remaining, created_at, updated_at
FROM users WHERE id = $1::uuid
`

type GetUserByIDRow struct {
	ID               uuid.UUID        `json:"id"`
	Username         string           `json:"username"`
	FullName         string           `json:"full_name"`
	Email            *string          `json:"email"`
	PhoneNumber      *string          `json:"phone_number"`
	Role             UserRole         `json:"role"`
	Status           UserStatus       `json:"status"`
	OnboardingStatus OnboardingStatus `json:"onboarding_status"`
	InvitesRemaining int32            `json:"invites_remaining"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.Status,
		&i.OnboardingStatus,
		&i.InvitesRemaining,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setInvitesRemaining = `-- name: SetInvitesRemaining :exec
UPDATE users SET invites_remaining = $1::int WHERE id = $2::uuid
`

type SetInvitesRemainingParams struct {
	InvitesRemaining int32     `json:"invites_remaining"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) SetInvitesRemaining(ctx context.Context, arg SetInvitesRemainingParams) error {
	_, err := q.db.Exec(ctx, setInvitesRemaining, arg.InvitesRemaining, arg.ID)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
SELECT update_user_info(
    $1::uuid,
    $2::text,
    $3::citext,
    $4::varchar,
    $5::text,
    $6::user_status
)
`

type UpdateUserInfoParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	FullName    *string        `json:"full_name"`
	Email       *string        `json:"email"`
	PhoneNumber *string        `json:"phone_number"`
	Password    *string        `json:"password"`
	Status      NullUserStatus `json:"status"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserInfo,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.Password,
		arg.Status,
	)
	return err
}
