// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warnings.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const recordWarningAck = `-- name: RecordWarningAck :one

SELECT record_warning_ack($1::uuid, $2::text,
    $3::text, $4::boolean,
    $5::uuid, $6::text,
    $7::bigint, $8::text) AS id
`

type RecordWarningAckParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	Category         string     `json:"category"`
	ReasonCode       string     `json:"reason_code"`
	Acknowledged     bool       `json:"acknowledged"`
	DebitAccountID   *uuid.UUID `json:"debit_account_id"`
	CounterpartyIban string     `json:"counterparty_iban"`
	AmountMinor      *int64     `json:"amount_minor"`
	Device           string     `json:"device"`
}

// Fraud-warning evidence (warning_acks, 00008).
func (q *Queries) RecordWarningAck(ctx context.Context, arg RecordWarningAckParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, recordWarningAck,
		arg.UserID,
		arg.Category,
		arg.ReasonCode,
		arg.Acknowledged,
		arg.DebitAccountID,
		arg.CounterpartyIban,
		arg.AmountMinor,
		arg.Device,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
