// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warning_rules.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const createWarningRule = `-- name: CreateWarningRule :one
INSERT INTO warning_rules (match_reason_code, match_min_band, category, headline, body,
                           severity, decision, required_ack, cooling_off_seconds, priority, active)
VALUES ($1::text, $2::text, $3::text,
        $4::text, $5::text, $6::text,
        $7::text, $8::boolean, $9::int,
        $10::int, $11::boolean)
RETURNING id
`

type CreateWarningRuleParams struct {
	MatchReasonCode   *string `json:"match_reason_code"`
	MatchMinBand      *string `json:"match_min_band"`
	Category          string  `json:"category"`
	Headline          string  `json:"headline"`
	Body              string  `json:"body"`
	Severity          string  `json:"severity"`
	Decision          string  `json:"decision"`
	RequiredAck       bool    `json:"required_ack"`
	CoolingOffSeconds int32   `json:"cooling_off_seconds"`
	Priority          int32   `json:"priority"`
	Active            bool    `json:"active"`
}

func (q *Queries) CreateWarningRule(ctx context.Context, arg CreateWarningRuleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createWarningRule,
		arg.MatchReasonCode,
		arg.MatchMinBand,
		arg.Category,
		arg.Headline,
		arg.Body,
		arg.Severity,
		arg.Decision,
		arg.RequiredAck,
		arg.CoolingOffSeconds,
		arg.Priority,
		arg.Active,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listWarningRules = `-- name: ListWarningRules :many

SELECT id, match_reason_code, match_min_band, category, headline, body, severity,
       decision, required_ack, cooling_off_seconds, priority, active, created_at, updated_at
FROM warning_rules
ORDER BY active DESC, priority DESC, created_at DESC
`

// Warning/decision rules (warning_rules, 00008) — the console fraud-policy CRUD.
// The rule engine itself lives in evaluate_transfer (hand-written wrapper in
// internal/db/bank.go); these are the operator maintenance queries.
// All rules (incl. inactive) for the console, best-first.
func (q *Queries) ListWarningRules(ctx context.Context) ([]WarningRule, error) {
	rows, err := q.db.Query(ctx, listWarningRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarningRule
	for rows.Next() {
		var i WarningRule
		if err := rows.Scan(
			&i.ID,
			&i.MatchReasonCode,
			&i.MatchMinBand,
			&i.Category,
			&i.Headline,
			&i.Body,
			&i.Severity,
			&i.Decision,
			&i.RequiredAck,
			&i.CoolingOffSeconds,
			&i.Priority,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWarningRuleActive = `-- name: SetWarningRuleActive :exec
UPDATE warning_rules SET active = $1::boolean WHERE id = $2::uuid
`

type SetWarningRuleActiveParams struct {
	Active bool      `json:"active"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetWarningRuleActive(ctx context.Context, arg SetWarningRuleActiveParams) error {
	_, err := q.db.Exec(ctx, setWarningRuleActive, arg.Active, arg.ID)
	return err
}

const updateWarningRule = `-- name: UpdateWarningRule :exec
UPDATE warning_rules
   SET match_reason_code   = $1::text,
       match_min_band      = $2::text,
       category            = $3::text,
       headline            = $4::text,
       body                = $5::text,
       severity            = $6::text,
       decision            = $7::text,
       required_ack        = $8::boolean,
       cooling_off_seconds = $9::int,
       priority            = $10::int,
       active              = $11::boolean
 WHERE id = $12::uuid
`

type UpdateWarningRuleParams struct {
	MatchReasonCode   *string   `json:"match_reason_code"`
	MatchMinBand      *string   `json:"match_min_band"`
	Category          string    `json:"category"`
	Headline          string    `json:"headline"`
	Body              string    `json:"body"`
	Severity          string    `json:"severity"`
	Decision          string    `json:"decision"`
	RequiredAck       bool      `json:"required_ack"`
	CoolingOffSeconds int32     `json:"cooling_off_seconds"`
	Priority          int32     `json:"priority"`
	Active            bool      `json:"active"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWarningRule(ctx context.Context, arg UpdateWarningRuleParams) error {
	_, err := q.db.Exec(ctx, updateWarningRule,
		arg.MatchReasonCode,
		arg.MatchMinBand,
		arg.Category,
		arg.Headline,
		arg.Body,
		arg.Severity,
		arg.Decision,
		arg.RequiredAck,
		arg.CoolingOffSeconds,
		arg.Priority,
		arg.Active,
		arg.ID,
	)
	return err
}
