{{- if and (not .Values.database.existingSecret) .Values.database.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: bank0
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.dsn | quote }}
{{- end }}
{{- if and (not .Values.auth.existingSecret) .Values.auth.jwtSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app.kubernetes.io/name: bank0
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.jwtSecret | quote }}
{{- end }}
