apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: bank0
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-portal
  labels:
    app.kubernetes.io/name: bank0
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
