// Command seedgen emits a self-contained, idempotent demo seed (db/seed_demo.sql)
// from a directory of real IBAN files (one IBAN per line, spaces allowed). It is a
// dev/demo tool, not part of the app build.
//
//	go run ./db/seedgen -assets /path/to/tf-backend/assets/ibans -out db/seed_demo.sql
//
// The generated SQL computes the shared bcrypt password/PIN hashes ONCE (not per
// row) and bulk-inserts users + accounts, so it loads ~1000 accounts in seconds
// rather than the minutes create_user/create_account would take (one bcrypt each).
// Accounts are funded and a sample of transfers is posted via the real deposit()/
// transfer() functions so balances and the ledger stay correct. Re-running is safe
// (ON CONFLICT for users/accounts; deposit()/transfer() are idempotency-keyed).
package main

import (
	"bufio"
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var ibanRE = regexp.MustCompile(`^[A-Z0-9]{15,34}$`) // matches the accounts.iban CHECK

var firstNames = []string{
	"Alice", "Bjorn", "Carla", "Dmitri", "Elena", "Felix", "Greta", "Hassan", "Ingrid", "Jonas",
	"Katja", "Liam", "Mira", "Niko", "Olga", "Pavel", "Quinn", "Rosa", "Stefan", "Tara",
	"Umar", "Vera", "Wouter", "Xenia", "Yusuf", "Zoe", "Anders", "Bea", "Cyril", "Dana",
	"Emil", "Farida", "Gustav", "Hanna", "Ivan", "Julia", "Karim", "Lena", "Marco", "Nadia",
}
var lastNames = []string{
	"Andersson", "Bergstrom", "Costa", "Dubois", "Eriksson", "Fischer", "Garcia", "Hansen", "Ivanov", "Jensen",
	"Kowalski", "Larsen", "Muller", "Nielsen", "Olsen", "Petrov", "Quintero", "Rossi", "Schmidt", "Toth",
	"Ucar", "Vidal", "Weber", "Novak", "Yilmaz", "Zhang", "Bianchi", "Moreau", "Nowak", "Horvath",
	"OBrien", "Lefebvre", "Sorensen", "Kovac", "Lindqvist", "Romano", "Walsh", "Janssen", "Berg", "Haas",
}
var descriptions = []string{
	"Rent", "Invoice payment", "Dinner", "Groceries", "Salary", "Gift", "Refund",
	"Subscription", "Consulting fee", "Loan repayment", "Utilities", "Travel",
}

func main() {
	assets := flag.String("assets", "", "directory of IBAN files (one IBAN per line)")
	out := flag.String("out", "db/seed_demo.sql", "output SQL path")
	maxAccts := flag.Int("accounts", 0, "cap on accounts (0 = use every unique IBAN)")
	rngSeed := flag.Int64("seed", 42, "RNG seed (deterministic output)")
	flag.Parse()
	if *assets == "" {
		fmt.Fprintln(os.Stderr, "-assets is required")
		os.Exit(2)
	}

	ibans, err := loadIBANs(*assets)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load ibans:", err)
		os.Exit(1)
	}
	if *maxAccts > 0 && len(ibans) > *maxAccts {
		ibans = ibans[:*maxAccts]
	}
	if len(ibans) == 0 {
		fmt.Fprintln(os.Stderr, "no valid IBANs found")
		os.Exit(1)
	}

	rng := rand.New(rand.NewSource(*rngSeed))

	// Group accounts into users of 1-4 accounts each.
	var users []user
	phoneCtr := 0
	for i := 0; i < len(ibans); {
		n := 1 + rng.Intn(4) // 1..4 accounts
		if i+n > len(ibans) {
			n = len(ibans) - i
		}
		idx := len(users)
		first := firstNames[rng.Intn(len(firstNames))]
		last := lastNames[rng.Intn(len(lastNames))]
		uname := fmt.Sprintf("%s.%s%d", strings.ToLower(first), strings.ToLower(last), idx)
		u := user{
			username: uname,
			fullname: first + " " + last,
			email:    fmt.Sprintf("%s@demo.example", uname),
			phone:    fmt.Sprintf("+46701%06d", phoneCtr),
		}
		phoneCtr++
		for j := 0; j < n; j++ {
			u.accts = append(u.accts, i+j)
		}
		users = append(users, u)
		i += n
	}

	// Per-account owner, deposit, limit.
	owner := make([]int, len(ibans))      // 1-based user index
	deposit := make([]int64, len(ibans))  // minor units
	limit := make([]int64, len(ibans))
	for ui, u := range users {
		for _, ai := range u.accts {
			owner[ai] = ui + 1
			deposit[ai] = int64(10000 + rng.Intn(2000000)) // €100 .. ~€20,000
			limit[ai] = 1000000                            // €10,000 transfer limit
		}
	}

	// Sample transfers between funded accounts (amount within debit's funds + limit).
	var txns []txn
	nTxn := len(ibans) / 4
	for k := 0; k < nTxn; k++ {
		d := rng.Intn(len(ibans))
		c := rng.Intn(len(ibans))
		if c == d {
			continue
		}
		maxAmt := deposit[d]
		if maxAmt > limit[d] {
			maxAmt = limit[d]
		}
		if maxAmt < 200 {
			continue
		}
		amt := int64(100 + rng.Intn(int(maxAmt/2))) // leave headroom so it can't overdraw
		txns = append(txns, txn{debit: d + 1, credit: c + 1, amount: amt, desc: descriptions[rng.Intn(len(descriptions))]})
	}

	// ---- emit -------------------------------------------------------------
	var b strings.Builder
	fmt.Fprintf(&b, `-- bank0 DEMO seed — GENERATED by db/seedgen (do not hand-edit). Idempotent.
-- Source: %d real IBANs from the tf-backend assets, cleaned (spaces stripped,
-- uppercased, deduped, validated against the accounts.iban CHECK).
-- %d customers, %d accounts, %d sample transfers.
--
-- Regenerate:  go run ./db/seedgen -assets <ibans-dir> -out db/seed_demo.sql
-- Apply:       psql "$DSN" -f db/seed_demo.sql      (or: task seed:demo)
--
-- All demo customers share password "password"; all account PINs are "1234".
-- For speed at scale the bcrypt hashes are computed ONCE here and reused, and
-- users/accounts are inserted directly (is_default handled below) — the small,
-- canonical named seed (db/seed.sql) still exercises the create_* functions.

DO $$
DECLARE
    v_pw    TEXT := crypt('password', gen_salt('bf', 10));
    v_pin   TEXT := crypt('1234', gen_salt('bf', 10));
    usernames TEXT[] := %s;
    fullnames TEXT[] := %s;
    emails    TEXT[] := %s;
    phones    TEXT[] := %s;
    a_iban    TEXT[]   := %s;
    a_owner   INT[]    := %s;
    a_deposit BIGINT[] := %s;
    a_limit   BIGINT[] := %s;
    t_debit   INT[]    := %s;
    t_credit  INT[]    := %s;
    t_amount  BIGINT[] := %s;
    t_desc    TEXT[]   := %s;
    uids UUID[] := '{}';
    aids UUID[] := '{}';
    v_uid UUID;
    v_aid UUID;
    v_default BOOLEAN;
    i INT;
BEGIN
    -- customers (shared bcrypt password hash) -----------------------------
    FOR i IN 1 .. array_length(usernames, 1) LOOP
        INSERT INTO users (username, password_hash, full_name, email, phone_number, role)
        VALUES (usernames[i]::citext, v_pw, fullnames[i], emails[i]::citext, phones[i], 'customer')
        ON CONFLICT (username) DO NOTHING;
        SELECT id INTO v_uid FROM users WHERE username = usernames[i]::citext;
        uids[i] := v_uid;
    END LOOP;

    -- accounts (shared bcrypt PIN; first account per user is the default) --
    FOR i IN 1 .. array_length(a_iban, 1) LOOP
        v_uid := uids[a_owner[i]];
        v_default := NOT EXISTS (SELECT 1 FROM accounts WHERE user_id = v_uid AND is_default);
        INSERT INTO accounts (user_id, kind, iban, pin_hash, transfer_limit_minor, is_default, currency, status)
        VALUES (v_uid, 'customer', a_iban[i], v_pin, a_limit[i], v_default, 'EUR', 'active')
        ON CONFLICT (iban) DO NOTHING;
        SELECT id INTO v_aid FROM accounts WHERE iban = a_iban[i];
        aids[i] := v_aid;
        -- opening deposit via the real function (idempotency key from the IBAN)
        PERFORM deposit('seed-dep-' || a_iban[i], v_aid, a_deposit[i], 'Opening deposit');
    END LOOP;

    -- sample activity (best-effort; skip any that would overdraw / exceed a limit)
    FOR i IN 1 .. COALESCE(array_length(t_debit, 1), 0) LOOP
        BEGIN
            PERFORM transfer('seed-txn-' || i::text, aids[t_debit[i]], aids[t_credit[i]],
                             t_amount[i], t_desc[i], 'transfer');
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
    END LOOP;

    RAISE NOTICE 'demo seed: %% customers, %% accounts, %% transfers attempted',
        array_length(usernames,1), array_length(a_iban,1), COALESCE(array_length(t_debit,1),0);
END $$;
`,
		len(ibans), len(users), len(ibans), len(txns),
		sqlTextArray(mapUsers(users, func(u user) string { return u.username })),
		sqlTextArray(mapUsers(users, func(u user) string { return u.fullname })),
		sqlTextArray(mapUsers(users, func(u user) string { return u.email })),
		sqlTextArray(mapUsers(users, func(u user) string { return u.phone })),
		sqlTextArray(ibans),
		sqlIntArray(owner),
		sqlInt64Array(deposit),
		sqlInt64Array(limit),
		sqlIntArrayFrom(txns, func(t txn) int { return t.debit }),
		sqlIntArrayFrom(txns, func(t txn) int { return t.credit }),
		sqlInt64ArrayFrom(txns, func(t txn) int64 { return t.amount }),
		sqlTextArray(mapTxns(txns, func(t txn) string { return t.desc })),
	)

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s: %d customers, %d accounts, %d transfers\n", *out, len(users), len(ibans), len(txns))
}

func loadIBANs(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		f, err := os.Open(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			s := strings.ToUpper(strings.Join(strings.Fields(sc.Text()), "")) // strip ALL whitespace
			if ibanRE.MatchString(s) {
				seen[s] = true
			}
		}
		f.Close()
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out) // deterministic
	return out, nil
}

type user struct {
	username, fullname, email, phone string
	accts                            []int
}

func mapUsers(us []user, f func(user) string) []string {
	out := make([]string, len(us))
	for i, u := range us {
		out[i] = f(u)
	}
	return out
}

type txn struct {
	debit, credit int
	amount        int64
	desc          string
}

func mapTxns(ts []txn, f func(txn) string) []string {
	out := make([]string, len(ts))
	for i, t := range ts {
		out[i] = f(t)
	}
	return out
}
func sqlIntArrayFrom(ts []txn, f func(txn) int) string {
	v := make([]int, len(ts))
	for i, t := range ts {
		v[i] = f(t)
	}
	return sqlIntArray(v)
}
func sqlInt64ArrayFrom(ts []txn, f func(txn) int64) string {
	v := make([]int64, len(ts))
	for i, t := range ts {
		v[i] = f(t)
	}
	return sqlInt64Array(v)
}

func sqlTextArray(ss []string) string {
	if len(ss) == 0 {
		return "ARRAY[]::TEXT[]"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = "'" + strings.ReplaceAll(s, "'", "''") + "'"
	}
	return "ARRAY[" + wrap(parts) + "]"
}
func sqlIntArray(v []int) string {
	if len(v) == 0 {
		return "ARRAY[]::INT[]"
	}
	parts := make([]string, len(v))
	for i, n := range v {
		parts[i] = fmt.Sprintf("%d", n)
	}
	return "ARRAY[" + wrap(parts) + "]"
}
func sqlInt64Array(v []int64) string {
	if len(v) == 0 {
		return "ARRAY[]::BIGINT[]"
	}
	parts := make([]string, len(v))
	for i, n := range v {
		parts[i] = fmt.Sprintf("%d", n)
	}
	return "ARRAY[" + wrap(parts) + "]"
}

// wrap joins with commas, newline-wrapping ~10 per line for readability.
func wrap(parts []string) string {
	var b strings.Builder
	for i, p := range parts {
		if i > 0 {
			b.WriteString(",")
			if i%10 == 0 {
				b.WriteString("\n        ")
			}
		}
		b.WriteString(p)
	}
	return b.String()
}
